/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'customerName' : string,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'scheduledTime' : Time,
  'createdAt' : Time,
  'address' : string,
  'phone' : string,
}
export interface BookingInput {
  'customerName' : string,
  'serviceType' : ServiceType,
  'scheduledTime' : Time,
  'address' : string,
  'phone' : string,
}
export interface BookingStats {
  'chimneyCleaning' : bigint,
  'hobService' : bigint,
  'chimneyInspection' : bigint,
  'chimneyRepair' : bigint,
  'stoveService' : bigint,
}
export type BookingStatus = { 'scheduled' : null } |
  { 'canceled' : null } |
  { 'completed' : null };
export type ServiceType = { 'chimneyCleaning' : null } |
  { 'hobService' : null } |
  { 'chimneyInspection' : null } |
  { 'chimneyRepair' : null } |
  { 'stoveService' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<[BookingInput], bigint>,
  'filterByCustomerName' : ActorMethod<[string], Array<Booking>>,
  'filterByDateRange' : ActorMethod<[Time, Time], Array<Booking>>,
  'filterByServiceType' : ActorMethod<[ServiceType], Array<Booking>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'getBookingStats' : ActorMethod<[], BookingStats>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];