/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'chimneyCleaning' : IDL.Null,
  'hobService' : IDL.Null,
  'chimneyInspection' : IDL.Null,
  'chimneyRepair' : IDL.Null,
  'stoveService' : IDL.Null,
});
export const Time = IDL.Int;
export const BookingInput = IDL.Record({
  'customerName' : IDL.Text,
  'serviceType' : ServiceType,
  'scheduledTime' : Time,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'canceled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'scheduledTime' : Time,
  'createdAt' : Time,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const BookingStats = IDL.Record({
  'chimneyCleaning' : IDL.Nat,
  'hobService' : IDL.Nat,
  'chimneyInspection' : IDL.Nat,
  'chimneyRepair' : IDL.Nat,
  'stoveService' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func([BookingInput], [IDL.Nat], []),
  'filterByCustomerName' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'filterByDateRange' : IDL.Func([Time, Time], [IDL.Vec(Booking)], ['query']),
  'filterByServiceType' : IDL.Func(
      [ServiceType],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getBookingStats' : IDL.Func([], [BookingStats], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'chimneyCleaning' : IDL.Null,
    'hobService' : IDL.Null,
    'chimneyInspection' : IDL.Null,
    'chimneyRepair' : IDL.Null,
    'stoveService' : IDL.Null,
  });
  const Time = IDL.Int;
  const BookingInput = IDL.Record({
    'customerName' : IDL.Text,
    'serviceType' : ServiceType,
    'scheduledTime' : Time,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'canceled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'serviceType' : ServiceType,
    'scheduledTime' : Time,
    'createdAt' : Time,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const BookingStats = IDL.Record({
    'chimneyCleaning' : IDL.Nat,
    'hobService' : IDL.Nat,
    'chimneyInspection' : IDL.Nat,
    'chimneyRepair' : IDL.Nat,
    'stoveService' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func([BookingInput], [IDL.Nat], []),
    'filterByCustomerName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'filterByDateRange' : IDL.Func([Time, Time], [IDL.Vec(Booking)], ['query']),
    'filterByServiceType' : IDL.Func(
        [ServiceType],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getBookingStats' : IDL.Func([], [BookingStats], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };